name: update changelog and api version

on:
  push:
    branches: [ main ]

  pull_request:
    # By default: opened, synchronize, or reopened.
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Check if changelog and api version were updated
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v19

      - name: Run step when a CHANGELOG.md didn't change
        uses: actions/github-script@v3
        if: ${{ !contains(steps.changed-files.outputs.modified_files, 'CHANGELOG.md') }}
        with:
          script: |
              core.setFailed('CHANGELOG.md should be modified')

      - name: Get *Plugin.json changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v19
        with:
          files: |
            *Plugin.json

      - name: Run step when a API VERSION didn't change
        uses: actions/github-script@v3
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        with:
          script: |
              core.setFailed('Version of RDK service API should be modified')
